# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cognitive-commons',
                'doc_host': 'https://LotsOfOrg.github.io',
                'git_url': 'https://github.com/LotsOfOrg/cognitive-commons',
                'lib_path': 'cognitive_commons'},
  'syms': {'cognitive_commons.core': {'cognitive_commons.core.foo': ('core.html#foo', 'cognitive_commons/core.py')}}}
