# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cognitive-commons',
                'doc_host': 'https://LotsOfOrg.github.io',
                'git_url': 'https://github.com/LotsOfOrg/cognitive-commons',
                'lib_path': 'cognitive_commons'},
  'syms': { 'cognitive_commons.core': {'cognitive_commons.core.foo': ('core.html#foo', 'cognitive_commons/core.py')},
            'cognitive_commons.data': {'cognitive_commons.data.foo': ('data.html#foo', 'cognitive_commons/data.py')},
            'cognitive_commons.evaluation': { 'cognitive_commons.evaluation.foo': ( 'evaluation.html#foo',
                                                                                    'cognitive_commons/evaluation.py')},
            'cognitive_commons.inference': {'cognitive_commons.inference.foo': ('inference.html#foo', 'cognitive_commons/inference.py')},
            'cognitive_commons.integration_tests': { 'cognitive_commons.integration_tests.foo': ( 'integration_tests.html#foo',
                                                                                                  'cognitive_commons/integration_tests.py')},
            'cognitive_commons.model': {'cognitive_commons.model.foo': ('model.html#foo', 'cognitive_commons/model.py')}}}
