"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_integration_tests.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/04_integration_tests.ipynb 3
def foo(): pass
